import './sax-js';

import './sax-js/attribute-name';
import './sax-js/attribute-no-space';
import './sax-js/attribute-unquoted';
import './sax-js/bom';
// import './sax-js/buffer-overrun';
import './sax-js/case';
import './sax-js/cdata-chunked';
import './sax-js/cdata-end-split';
import './sax-js/cdata-fake-end';
import './sax-js/cdata-multiple';
import './sax-js/cdata';
import './sax-js/cyrillic';
import './sax-js/duplicate-attribute';
import './sax-js/emoji';
// import './sax-js/end_empty_stream';
import './sax-js/entities'
import './sax-js/entity-mega';
import './sax-js/entity-nan';
import './sax-js/flush';
import './sax-js/issue-23';
import './sax-js/issue-30';
import './sax-js/issue-35';
import './sax-js/issue-47';
import './sax-js/issue-49';
import './sax-js/issue-84';
import './sax-js/issue-86';
// import './sax-js/not-string';
import './sax-js/opentagstart';
// import './sax-js/parser-position';
import './sax-js/script-close-better';
import './sax-js/script';
import './sax-js/self-closing-child-strict';
import './sax-js/self-closing-child';
import './sax-js/self-closing-tag';
import './sax-js/stand-alone-comment';
import './sax-js/stray-ending';
import './sax-js/trailing-attribute-no-value';
import './sax-js/trailing-non-whitespace';
import './sax-js/unclosed-root';
import './sax-js/unquoted';
// import './sax-js/utf8-split';
// import './sax-js/xml-internal-entities';
// import './sax-js/xml_entities';
import './sax-js/xmlns-as-tag-name';
import './sax-js/xmlns-issue-41';
import './sax-js/xmlns-rebinding';
import './sax-js/xmlns-strict';
import './sax-js/xmlns-unbound-element';
import './sax-js/xmlns-unbound';
import './sax-js/xmlns-xml-default-ns';
import './sax-js/xmlns-xml-default-prefix-attribute';
import './sax-js/xmlns-xml-default-prefix';
import './sax-js/xmlns-xml-default-redefine';
